export default interface Animal {
  id: number,
  organization: string,
  registration_no: string,
  registration_date: string,
  status: string | null,
  image_url: string | null,
  birth_date: string | null,
  name: string | null,
  species: string | null,
  gender: string | null,
  weight: number,
  microchip_id: string | null,
  chip_install_date: string | null,
  allergy: string | null | null,
  food: string | null | null,
  comments: string | null | null,
  mod_time: string | null,
  breed: string | null,
  color: string | null,
}
