version: "3.8"
services:
  gis-backend:
    build:
      context: .
    ports:
      - 8081:8081
      - 9229:9229
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./src:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    command: npm run debug
