/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import AnimalItem from '../interfaces/animalItem.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {AnimalItem};
export const AnimalItemSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "animalId": {
      "type": "number"
    },
    "id": {
      "type": "number"
    },
    "itemName": {
      "type": "string"
    }
  },
  "required": [
    "animalId",
    "id",
    "itemName"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isAnimalItem = ajv.compile(AnimalItemSchema) as ValidateFunction<AnimalItem>;
export default function validate(value: unknown): AnimalItem {
  if (isAnimalItem(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isAnimalItem.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'AnimalItem'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
