/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import Breed from '../interfaces/breed.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Breed};
export const BreedSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "abbreviation": {
      "type": "string"
    },
    "id": {
      "type": "number"
    },
    "value": {
      "type": "string"
    }
  },
  "required": [
    "abbreviation",
    "id",
    "value"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isBreed = ajv.compile(BreedSchema) as ValidateFunction<Breed>;
export default function validate(value: unknown): Breed {
  if (isBreed(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isBreed.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Breed'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
