/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from 'util';
import BreedWithSpecies from '../interfaces/breedWithSpecies.interface';
import Ajv = require('ajv');

export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {BreedWithSpecies};
export const BreedWithSpeciesSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "abbreviation": {
      "type": "string"
    },
    "id": {
      "type": "number"
    },
    "speciesId": {
      "type": "number"
    },
    "speciesValue": {
      "type": "string"
    },
    "value": {
      "type": "string"
    }
  },
  "required": [
    "abbreviation",
    "id",
    "speciesId",
    "speciesValue",
    "value"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isBreedWithSpecies = ajv.compile(BreedWithSpeciesSchema) as ValidateFunction<BreedWithSpecies>;
export default function validate(value: unknown): BreedWithSpecies {
  if (isBreedWithSpecies(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isBreedWithSpecies.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'BreedWithSpecies'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
