/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from 'util';
import Color from '../interfaces/color.interface';
import Ajv = require('ajv');

export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Color};
export const ColorSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "id": {
      "type": "number"
    },
    "speciesId": {
      "type": "number"
    },
    "speciesName": {
      "type": "string"
    },
    "value": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "speciesId",
    "speciesName",
    "value"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isColor = ajv.compile(ColorSchema) as ValidateFunction<Color>;
export default function validate(value: unknown): Color {
  if (isColor(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isColor.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Color'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
