/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from 'util';
import MedicationEvent from '../interfaces/eventMedication.interface';
import Ajv = require('ajv');

export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {MedicationEvent};
export const MedicationEventSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "default": {
      "defaultProperties": [
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "surname": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "id",
        "name",
        "surname"
      ],
      "type": "object"
    }
  },
  "properties": {
    "animalId": {
      "type": "number"
    },
    "author": {
      "$ref": "#/definitions/default"
    },
    "comments": {
      "type": [
        "null",
        "string"
      ]
    },
    "dateTime": {
      "type": [
        "null",
        "string"
      ]
    },
    "expenses": {
      "type": [
        "null",
        "number"
      ]
    },
    "id": {
      "type": "number"
    },
    "treatment": {
      "type": "string"
    }
  },
  "required": [
    "animalId",
    "author",
    "comments",
    "dateTime",
    "expenses",
    "id",
    "treatment"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isMedicationEvent = ajv.compile(MedicationEventSchema) as ValidateFunction<MedicationEvent>;
export default function validate(value: unknown): MedicationEvent {
  if (isMedicationEvent(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isMedicationEvent.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'MedicationEvent'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
