/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import Event from '../interfaces/event.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Event};
export const EventSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "EventGroup": {
      "enum": [
        "General",
        "Medical"
      ],
      "type": "string"
    },
    "EventType": {
      "enum": [
        "CheckIn",
        "CheckOut",
        "Died",
        "Found",
        "GenderElimination",
        "GivenAway",
        "Inspection",
        "LocationChange",
        "Medication",
        "Microchipping",
        "Prophylaxis",
        "Surgery",
        "TemporaryCare"
      ],
      "type": "string"
    }
  },
  "properties": {
    "animalId": {
      "type": "number"
    },
    "author": {
      "type": [
        "null",
        "string"
      ]
    },
    "createTime": {
      "type": [
        "null",
        "string"
      ]
    },
    "dateTime": {
      "type": [
        "null",
        "string"
      ]
    },
    "group": {
      "$ref": "#/definitions/EventGroup"
    },
    "id": {
      "type": "number"
    },
    "type": {
      "$ref": "#/definitions/EventType"
    }
  },
  "required": [
    "animalId",
    "author",
    "createTime",
    "dateTime",
    "group",
    "id",
    "type"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isEvent = ajv.compile(EventSchema) as ValidateFunction<Event>;
export default function validate(value: unknown): Event {
  if (isEvent(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isEvent.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Event'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
