/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import EventType from '../interfaces/eventType.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {EventType};
export const EventTypeSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "id": {
      "type": "number"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "type"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isEventType = ajv.compile(EventTypeSchema) as ValidateFunction<EventType>;
export default function validate(value: unknown): EventType {
  if (isEventType(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isEventType.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'EventType'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
