/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import Event from '../interfaces/event.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Event};
export const EventSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "Category": {
      "enum": [
        "GENERAL",
        "MEDICAL"
      ],
      "type": "string"
    },
    "default": {
      "defaultProperties": [
      ],
      "properties": {
        "id": {
          "type": "number"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "type"
      ],
      "type": "object"
    }
  },
  "properties": {
    "animal": {
      "type": "number"
    },
    "category": {
      "$ref": "#/definitions/Category"
    },
    "comments": {
      "type": [
        "null",
        "string"
      ]
    },
    "dateTime": {
      "type": [
        "null",
        "string"
      ]
    },
    "expenses": {
      "type": [
        "null",
        "number"
      ]
    },
    "id": {
      "type": "number"
    },
    "type": {
      "$ref": "#/definitions/default"
    }
  },
  "required": [
    "animal",
    "category",
    "comments",
    "dateTime",
    "expenses",
    "id",
    "type"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isEvent = ajv.compile(EventSchema) as ValidateFunction<Event>;
export default function validate(value: unknown): Event {
  if (isEvent(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isEvent.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Event'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
