/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import EventHandOver from '../interfaces/eventHandOver.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {EventHandOver};
export const EventHandOverSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "default": {
      "defaultProperties": [
      ],
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": [
            "null",
            "string"
          ]
        },
        "surname": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "required": [
        "id",
        "name",
        "surname"
      ],
      "type": "object"
    }
  },
  "properties": {
    "animalId": {
      "type": "number"
    },
    "author": {
      "$ref": "#/definitions/default"
    },
    "date": {
      "type": [
        "null",
        "string"
      ]
    },
    "formerOwnerId": {
      "type": "number"
    },
    "id": {
      "type": "number"
    },
    "reason": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "required": [
    "animalId",
    "author",
    "date",
    "formerOwnerId",
    "id",
    "reason"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isEventHandOver = ajv.compile(EventHandOverSchema) as ValidateFunction<EventHandOver>;
export default function validate(value: unknown): EventHandOver {
  if (isEventHandOver(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isEventHandOver.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'EventHandOver'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
