/* tslint:disable */
// generated by typescript-json-validator
import { inspect } from 'util';
import FormerAnimalOwner from '../interfaces/formerAnimalOwner.interface';
import Ajv = require('ajv');

export const ajv = new Ajv({
    allErrors: true,
    coerceTypes: false,
    format: 'fast',
    nullable: true,
    unicode: true,
    uniqueItems: true,
    useDefaults: true,
});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export { FormerAnimalOwner };
export const FormerAnimalOwnerSchema = {
    $schema: 'http://json-schema.org/draft-07/schema#',
    defaultProperties: [],
    properties: {
        id: {
            type: 'number',
        },
        name: {
            type: 'string',
        },
        phone: {
            type: 'string',
        },
        surname: {
            type: 'string',
        },
    },
    required: ['id', 'name'],
    type: 'object',
};
export type ValidateFunction<T> = ((data: unknown) => data is T) &
    Pick<Ajv.ValidateFunction, 'errors'>;
export const isFormerAnimalOwner = ajv.compile(
    FormerAnimalOwnerSchema
) as ValidateFunction<FormerAnimalOwner>;
export default function validate(value: unknown): FormerAnimalOwner {
    if (isFormerAnimalOwner(value)) {
        return value;
    }
    throw new Error(
        `${ajv.errorsText(
            isFormerAnimalOwner.errors!.filter((e: any) => e.keyword !== 'if'),
            { dataVar: 'FormerAnimalOwner' }
        )}\n\n${inspect(value)}`
    );
}
