/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import GivenAwayEvent from '../interfaces/givenAwayEvent.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {GivenAwayEvent};
export const GivenAwayEventSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "animalId": {
      "type": "number"
    },
    "date": {
      "type": [
        "null",
        "string"
      ]
    },
    "formerOwnerId": {
      "type": "number"
    },
    "id": {
      "type": "number"
    },
    "reason": {
      "type": [
        "null",
        "string"
      ]
    }
  },
  "required": [
    "animalId",
    "date",
    "formerOwnerId",
    "id",
    "reason"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isGivenAwayEvent = ajv.compile(GivenAwayEventSchema) as ValidateFunction<GivenAwayEvent>;
export default function validate(value: unknown): GivenAwayEvent {
  if (isGivenAwayEvent(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isGivenAwayEvent.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'GivenAwayEvent'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
