/* eslint-disable */
/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import Organization from '../interfaces/organization.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Organization};
export const OrganizationSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "city": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "id": {
      "type": "number"
    },
    "modTime": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "streetAddress": {
      "type": "string"
    }
  },
  "required": [
    "city",
    "country",
    "id",
    "modTime",
    "name",
    "phone",
    "streetAddress"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isOrganization = ajv.compile(OrganizationSchema) as ValidateFunction<Organization>;
export default function validate(value: unknown): Organization {
  if (isOrganization(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isOrganization.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Organization'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
