/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import Status from '../interfaces/status.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Status};
export const StatusSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "id": {
      "type": "string"
    },
    "value": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "value"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isStatus = ajv.compile(StatusSchema) as ValidateFunction<Status>;
export default function validate(value: unknown): Status {
  if (isStatus(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isStatus.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Status'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
