/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import Translation from '../interfaces/translation.interface';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {Translation};
export const TranslationSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "properties": {
    "id": {
      "type": [
        "string",
        "number"
      ]
    },
    "value": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "value"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isTranslation = ajv.compile(TranslationSchema) as ValidateFunction<Translation>;
export default function validate(value: unknown): Translation {
  if (isTranslation(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isTranslation.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'Translation'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
